name: Compile PDF
on:
  push:

jobs:
  compile:
    name: Compile Notebooks
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout actions
      uses: actions/checkout@v3
    
    - name: Python Setup
      run: |
        pip install virtualenv
        cd ${{ github.workspace }}
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r ./requirements.txt
        cd -
    
    - name: Install Pandoc
      shell: bash
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14/pandoc-2.14-1-amd64.deb
        sudo dpkg -i pandoc-2.14-1-amd64.deb
        sudo apt-get install -f
        rm pandoc-2.14-1-amd64.deb
    
    - name: Install xelatex
      run: |
        sudo apt update
        sudo apt install texlive-xetex
    
    - name: Copy template
      run: |
        cd ${{ github.workspace }}
        cp templates/* .venv/share/jupyter/nbconvert/templates/latex/
    
    - name: Compile PDF templated
      shell: bash
      run: |
        cd ${{ github.workspace }}
        source .venv/bin/activate 
        python3 -m bookbook.latex --output-file relatorio.pdf --pdf --template templates/*

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}