name: Compile PDF
on:
  push:

jobs:
  compile:
    name: Compile Notebooks
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout actions
      uses: actions/checkout@v3
    
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "./requirements.txt"
    
    - name: Install Pandoc
      shell: bash
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.14/pandoc-2.14-1-amd64.deb
        sudo dpkg -i pandoc-2.14-1-amd64.deb
        sudo apt-get install -f
    
    - name: Install xelatex
      run: |
        sudo apt-get install texlive-xetex
    
    - name: Compile PDF
      shell: bash
      run: python3 -m bookbook.latex --pdf --output-file relatorio.pdf

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}