name: Compile PDF
on:
  push:

jobs:
  compile:
    name: Compile Notebooks
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout actions
      uses: actions/checkout@v3
    
    - name: Install Requirements
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pip install -r requirements.txt
    
    - name: Compile PDF
      shell: bash
      run: python3 -m bookbook.latex --pdf --output-file relatorio.pdf

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}